### ISSUE TITLE
`haxelib path` order is not consistent with real haxelib

### ISSUE THREAD

**Issue by Gama11** [lix-pm/lix.client#103]
```
>haxelib path random
C:\HaxeToolkit\haxe\lib\random/1,4,1/src/
-D random=1.4.1

>npx haxelib path random
-D random=1.4.1
C:/Users/Jens/AppData/Roaming/haxe/haxe_libraries/random/1.4.1/haxelib/src/

```

As you can see, the order is reversed for the Haxelib shim. This could potentially be problematic if there's any code making assumptions about the first line being the path?

**Comment by back2dos** [comment]
This is echoed in the order in which lix puts it in the hxml.

**Comment by back2dos** [comment]
Works now, if you reinstall the affected dependencies.
