### ISSUE TITLE
haxe_libraries resolver ignore --cwd option

### ISSUE THREAD

**Issue by mikicho** [lix-pm/lix.client#107]
It seems like it searches `haxe_libraries` in `pwd` and not in `cwd`

Reproducible example:
1. clone this repo: https://github.com/mikicho/reproduce
2. run: `haxe --connect 6000 --cwd src/server server.hxml` from root

**Comment by kevinresol** [comment]
You should put your haxe_libraries folder and  .haxerc at the root folder

**Comment by mikicho** [comment]
Thanks, but because I usually build both client and server with haxe I'm used to creating a `components` folder which contains a folder for each "side" (`client`, `server` and maybe `shared` which contains interfaces and such).
So it seems like for me a better to separate the `haxe_libraries` (so dependencies from one component won't interfere with the other) and `haxerc` (so I'll be able to use different versions of haxe if needed) isn't?
But maybe I'm trying to over-optimizing/engineering things.
There are some best-practices you (and maybe @back2dos ) can recommend for?

**Comment by back2dos** [comment]
Well, `--cwd` sets the cwd for the haxe process and I don't really want to overload its meaning. Also, a build may contain multiple `--cwd`s, and if `--cwd` were interpreted as suggested, it would become ambiguous where to even look for the .haxerc file (and thus which haxe version to use).

While to some degree I see why having separate dependency versioning for server and client might be nice, it can also lead to incompatibility. Also `shared` doesn't fit in there. You can't compile with a mix of `shared/haxe_libraries` and `client/haxe_libraries`.

If you do need two different versions of the same lib, you can do `lix install url:lib#version as otherName` and refer to it via `-lib otherName`.

**Comment by mikicho** [comment]
I see, thanks!
