### ISSUE TITLE
lix help

### ISSUE THREAD

**Issue by Gama11** [lix-pm/lix.client#113]
I think it wouldn't hurt to have a `help` command, because this keeps happening to me...

```
> npx lix help
unknown command help
```

Or maybe just do what Haxe does and output the help after unknown commands.

**Comment by back2dos** [comment]
> Or maybe just do what Haxe does and output the help after unknown commands.

Yeah, I don't really like that. Integrated consoles tend to show only a dozen lines or so and this pushes error messages off screen.
