### ISSUE TITLE
Does lix support extraParams.hxml ?

### ISSUE THREAD

**Issue by melMass** [lix-pm/lix.client#117]
Sorry if it was asked already but I could not find it, is there a way to define something like haxelib's `extraParams.hxml` in Lix ?

**Comment by Gama11** [comment]
That should work. Why do you ask, did you run into problems with it?

**Comment by melMass** [comment]
It’s not firing on my end.
I have a `—macro` flag in extraparams but I don’t understand how lix can be aware of it since I’m using haxelibs structure:
- Root Library folder > src > Root Library name

Extraparams being in the root folder and `src` the lix -cp source path..

Do you understand ?

Thanks

**Comment by Gama11** [comment]
When you install a library with lix, it copies the contents of `extraParams.hxml` into the corresponding HXML file in `haxe_libraries`. Example: https://github.com/vshaxe/vshaxe/blob/9125a4a2231bcb56e278aaa7303388636ea8fb80/haxe_libraries/hxnodejs.hxml#L4-L6

**Comment by benmerckx** [comment]
If you're using lix to develop a library you can include extraParams yourself:
https://github.com/benmerckx/genes/blob/60d2b85d4cb7859aea1f310da4b57dd890bb79bf/haxe_libraries/genes.hxml#L1

Or pass to the compiler:
`haxe extraParams.hxml -cp src ...`

**Comment by back2dos** [comment]
Also, if you use `lix dev library_name path/to/library`, then if `extraParams.hxml` is present, you will find that `haxe_libraries/library_name.hxml` contains `path/to/library/extraParams.hxml`.

Does this answer your question?

**Comment by melMass** [comment]
Yes that was it! 
As it's a local library for now I was using the trick in the readme (manually add a file to the haxe-libraries with a cp command pointing to your lib) using lix dev seems to solve that thanks
