### ISSUE TITLE
wrong neko version bundled with haxe 4.0.5 ?

### ISSUE THREAD

**Issue by bablukid** [lix-pm/lix.client#131]
It looks like using haxe 4.0.5 in a lix project installs neko 2.2

But haxe 4 shoud be shipped with neko 2.3 

I get errors like "Uncaught exception - load.c(237) : Failed to load library : std.ndll"  because I try to execute neko 2.3 bytecode with a neko 2.2 vm ( well, I guess... )

**Comment by Gama11** [comment]
Sounds like your lix is too old?

**Comment by bablukid** [comment]
I removed my standard system wide haxe and neko install ( i'm on Ubuntu )
then I reinstalled lix, got v15.8.15

**Comment by bablukid** [comment]
ok , found the problem. After deleting my "haxe" folder in my home, it forced lix to reinstall haxe 4.0.5 and neko 2.3, now I got neko 2.3.
