### ISSUE TITLE
Can't install specific nightly build

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#144]
lix tells me to run a command, but won't accept it

```
Unable to resolve nightly version nightly build 4ac9031 locally, install it first with `lix install haxe nightly build 4ac9031`
$ lix install haxe nightly build 4ac9031
too many arguments
```

**Comment by back2dos** [comment]
Ah. It's `lix install haxe 4ac9031`, but yeah, the error message needs correcting. That said, it looks like that build is gone (because the nightlies are deleted after a year).
