### ISSUE TITLE
add to versions?

### ISSUE THREAD

**Issue by nanjizal** [lix-pm/lix.client#147]
Currently 'versions' support haxe and haxelib as I pulled them, since not currently using lix thought safer to suggest lix user implement. Versions seem to be getting new features would be worthwhile also working out if we can pull additional haxe specific features, but perhaps they are best catered for via lix. Was not sure which repo should add this issue in. 
https://github.com/bit101/version/blob/master/version

**Comment by back2dos** [comment]
Hmm, seems like if anything, this should be done in the other repo.
