### ISSUE TITLE
[NPM] Lix package

### ISSUE THREAD

**Issue by ghost** [lix-pm/lix.client#152]
Greetings,

after installing Lix as NPM dependency I get a [Critical Vulnerability](https://www.npmjs.com/advisories/1306) and I think something should be done about it.

**Comment by RichardBray** [comment]
I think this has been fixed now. I use Lix for one of my projects and I don't see this issue anymore.

@flammehawk can you confirm this?

**Comment by kevinresol** [comment]
No this is not fixed and there is no plan to fix it in short term.

**Comment by back2dos** [comment]
Duplicate of #167
