### ISSUE TITLE
Windows Warning after installing lix

### ISSUE THREAD

**Issue by pawel-miczka** [lix-pm/lix.client#154]
I'm getting error when I'm trying to install lix:

![image](https://user-images.githubusercontent.com/5631954/100472078-d980cc80-30db-11eb-88d2-eb88f403305c.png)

I'm installing it via node.js also installed via .exe 14.15.1 (which is LTS)

**Comment by back2dos** [comment]
On Windows, lix (or rather haxeshim) attempts to provide a haxe.exe, as detailed here: https://github.com/lix-pm/haxeshim#windows

This may be prevented by security restrictions (e.g. anti virus). In that case, things will still work just fine, with the exception of batch scripts (as explained above) or any tools that may be hardcoded to assume the haxe executable to have a .exe extension (which is rather rare, but not unheard of). Unfortunately, there's not much we can do about that
