### ISSUE TITLE
Quoting broken on windows

### ISSUE THREAD

**Issue by back2dos** [lix-pm/lix.client#16]
Using [single quotes](https://github.com/lix-pm/lix.client/commit/865be189640f5697cea754212f8801f20df4cdd1#diff-ecbe53c768bcd986fac108ce3117c58dR125) to escape URL breaks on Windows. 

The simplest solution would be to use double quotes. That said I wonder: do we need quotes at all? The commit says it's to deal with `&` but given that whitespace is illegal in URLs it is safe to assume that no isolated `&` is generated and given that `&` is a valid character in file names, I don't think any OS can just randomly interpret `&` occurring mid-argument, no?

**Comment by kevinresol** [comment]
Well at least macos chokes on the & symbol. I'll have a look

**Comment by kevinresol** [comment]
Because `&` is used to run several commands asynchronously on shell. ([ref](http://bashitout.com/2013/05/18/Ampersands-on-the-command-line.html))

**Comment by back2dos** [comment]
TIL: whitespace is overrated :D

**Comment by kevinresol** [comment]
btw, powershell handles single quotes, just not command prompt.
