### ISSUE TITLE
Unknown scheme in url

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/lix.client#17]
Trying to install the libraries of `examples-todomvc`. I went the npm route and noticed it points to an older version of switchx/haxeshim (which gives you an error about `scoped` not being a valid value for `resolveLibs`). So I changed the dependencies to:
```
  "dependencies": {
    "less": "2.7.2",
    "lix.pm": "^0.9.1",
    "switchx": "^0.12.0"
  }
```
Now when I try to install I get the following:
```
switchx install && lix download
  ... already downloaded!
Now using official release 3.4.2
digging: C:\projects\examples-todomvc
config found: true
digging: C:\projects\examples-todomvc
config found: true
lix --silent download 'https://github.com/MVCoconut/coconut.data/archive/0a38a12b2957d3acea610f7d267c275d462a2ec8.tar.gz' into coconut.data/0.4.1/github/0a38a12b2957d3acea610f7d267c275d462a2ec8
digging: C:\projects\examples-todomvc
config found: true
Unknown scheme in url 'https://github.com/MVCoconut/coconut.data/archive/0a38a12b2957d3acea610f7d267c275d462a2ec8.tar.gz'
````
Running that `lix --silent download` command by itself gives me the same error.

**Comment by kevinresol** [comment]
Well yes this is broken due to https://github.com/lix-pm/lix.client/issues/16 , assuming you are on windows. 

The single quotes needs to be replaced by double quotes

**Comment by benmerckx** [comment]
Right, installing it again now writes the file without quotes. Thanks!

**Comment by kevinresol** [comment]
Let's keep this open for a while, I need to remove the debug traces and update the example.
