### ISSUE TITLE
Error when starting Haxe after installing with lix on a fresh machine

### ISSUE THREAD

**Issue by anissen** [lix-pm/lix.client#171]
I am setting up a brand new machine (MacBook Pro M1X) and _of course_ the first thing I set up is Lix and Haxe. However, when I try to run Haxe after installing it with Lix I get the following error:

`
haxelib path: Failed to call /Users/anders/haxe/versions/4.2.4/haxelib because Error: spawnSync /Users/anders/haxe/versions/4.2.4/haxelib Unknown system error -86
`

What I did:
1. `brew install npm`
2. `npm install -g lix`
3. `lix dowload` (in a local instance of https://github.com/anissen/cosy)

Afterwards I tried installing Haxe using `brew install haxe` and that worked fine.

**Comment by kevinresol** [comment]
Try `softwareupdate --install-rosetta`

**Comment by anissen** [comment]
It worked! 🎉  Thank you so much @kevinresol, you've made my day! 😄
