### ISSUE TITLE
Don't use JS apis

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [lix-pm/lix.client#174]
Don't use JS apis, use cross platform apis so it can be built across targets. NodeJS incurs overhead, and nobody likes npm.

**Comment by back2dos** [comment]
This is sorta "planned", but it's a non-trivial undertaking, especially given how limited the cross platform APIs are regarding env and IO. PRs are naturally welcome ;)

Also, in the future, please keep irrelevant opinions to yourself.
