### ISSUE TITLE
Allow custom git haxe installs. 

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [lix-pm/lix.client#175]
Allow, someway or somehow, to download custom haxe libs from github. Haxe has actions, so any fork of Haxe builds packages via actions, [as seen here](https://github.com/TheDrawingCoder-Gamer/haxe4java/actions/runs/2612161519). I know it's a headache to implement this, but I don't want to make a rube goldberg machine just to support this.

**Comment by kevinresol** [comment]
You can create a folder in `~/haxe/versions` and link that in your `.haxerc`
For example you have `~/haxe/versions/custom` and `"version": "custom"` in `.haxerc`

**Comment by TheDrawingCoder-Gamer** [comment]
hm, I'll probably have to write my own downloader then.
