### ISSUE TITLE
Haxelib version seems to be broken

### ISSUE THREAD

**Issue by ConfidantCommunications** [lix-pm/lix.client#181]
What I did:
`lix install haxelib:lime#7.9.0`

I expected it to install, per the lix instructions. Instead it said "zsh: no matches found: haxelib:lime#7,9,0"

**Comment by back2dos** [comment]
Seems zsh specific. Can you try escaping `haxelib:lime#7.9.0` with single / double quotes (I'm not too familiar with the various shell syntaxes).

**Comment by ConfidantCommunications** [comment]
This worked: lix install "haxelib:lime#7.9.0"
Thanks Juraj!
