### ISSUE TITLE
How to configure global repo location with lix, haxelib setup has no effect

### ISSUE THREAD

**Issue by neimanpinchas** [lix-pm/lix.client#189]
I used to store my global haxelib on a portable USB for development offline.

When I had to upgrade to haxe 4.3 on linux, I had been advised to use lix.

Due to my nature of offline development a global repo is more usefull for me than having local repos.

I've tried to run haxelib setup /media/usb/haxe but haxelib config still show ~/haxe

How can I change the location for global haxelib location?

**Comment by AlexHaxe** [comment]
duplicate of #116

**Comment by neimanpinchas** [comment]
Thanks, I tried to search, prob was missing keywords

**Comment by neimanpinchas** [comment]
Since there are many issues pointing to this one, I would suggest haxeshim to display a message when running haxelib setup please notice, this will have no effect and instead you can change the environment varible HAXE_PATH to you prefered path
