### ISSUE TITLE
Git Repo Support

### ISSUE THREAD

**Issue by cmandlbaur** [lix-pm/lix.client#19]
I would like to start using lix, but my main constraint for this is support for pointing directly at a git repo url.

Quick look at the source and I feel there might be 2 shortcuts that could taken here:
1. Install via haxelib git support.
2. At least allow for switching out the url for gitlab, many private installations are using their enterprise version.

Dont mind trying to implement, just need to some guidance on whether there are other plans for this and if there are already plans for this.

**Comment by back2dos** [comment]
I actually like the idea of being able to point to a different gitlab server. We could simply use the `host` of the `Url` for that:

- `gitlab:<owner>/<repo>[#<brach|tag|sha>]` - will get the library from gitlab.com
- `gitlab://<host>/<owner>/<repo>[#<brach|tag|sha>]` - will get the library from a GitLab instance running on the specified host

**Comment by kevinresol** [comment]
Maybe we also want generic git support?

**Comment by back2dos** [comment]
Ok, so 0.9.3 supports specifying alternative hosts in gitlab and haxelib URLs.

As for true git support, I'm all for it, so long as it is reliable. Maybe https://github.com/lix-pm/lix.client/issues/5 would be a solution (given that submodules are exactly tracked in the parent repo)?

**Comment by kevinresol** [comment]
getting this on 0.9.3
```
lix --silent download 'haxelib:travix#0.9.0' into travix/0.9.0/haxelib
Failed to download lib.haxe.org/p/travix/0.9.0/download/ because connect ECONNREFUSED 127.0.0.1:80
```

**Comment by back2dos** [comment]
Hmm, works fine on my end. Any idea why lib.haxe.org becomes 127.0.0.1?

**Comment by kevinresol** [comment]
I am not very sure. It was running on GitLab CI. 
0.9.2 is fine though. I'll have to check.

**Comment by back2dos** [comment]
Well, the good news is I just got the same on Travis \o/

**Comment by back2dos** [comment]
Ok, 0.9.4 fixes the haxelib issue.

**Comment by grosmar** [comment]
I would need also git support as there are private repos that I can use only through git.
What about your proposal of #5  to solve that way?

**Comment by back2dos** [comment]
Closing in favor of #5.

**Comment by back2dos** [comment]
Upon second thought, this is a different matter: git versions could just be stored globally (without history), addressable per commit, while submodules will go into the scope itself.

**Comment by back2dos** [comment]
This ended up slightly awkward, because git doesn't allow addressing arbitrary commits (by default at least). So there's a global cache for all repos, where their whole history is fetched, and then the right commit is checked out. This will perform quite poorly for large histories.
