### ISSUE TITLE
Bundling lix into a single file.

### ISSUE THREAD

**Issue by back2dos** [lix-pm/lix.client#20]
To whom it may concern: I have just published v0.10.2 which (after two failed attempts seems to run just fine on travis and) has its dependencies bundled and doesn't need to get them through npm. 

The main reason for this is speed. On a decent connection I get this:

- `Measure-Command {npm install lix.pm@0.10.2}` -> `TotalMilliseconds : 1150.8477`
- `Measure-Command {npm install lix.pm@0.9.4}` -> `TotalMilliseconds : 3949.246`

It makes for a reasonably sized bundle (~450K which could be minified to ~180K), because lix has just two highly stable npm dependencies and I don't see the numbers increasing drastically in the foreseeable future - if anything I'm hoping we'll have streaming zip and tar decompression ported to Haxe some day.

Anyway: I'd like to hear your opinions on pursuing this approach and hear about any issues arising from this ;)

**Comment by kevinresol** [comment]
I don't really have any opinion, given that nothing breaks. But 3 seconds is actually nothing in my CI build. I would rather like to have "lix download" in parallel.

**Comment by sh-dave** [comment]
Less (or bundled in this case) dependencies is always a win as far as i'm concerned. Not really for speed or size reasons, but less stuff that can go wrong.

**Comment by back2dos** [comment]
This is now properly set up.
