### ISSUE TITLE
Unknown scheme in url 'haxelib:travix#0.9.0'

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#22]
Got this on windows w/ lix 0.10.2, when running `lix download` with hxml directive `lix --silent download 'haxelib:travix#0.9.0' into travix/0.9.0/haxelib`
Is it due to the extra quote?

**Comment by back2dos** [comment]
Yeah, that's from the quoting you introduced to make `&` pass on Mac. But windows doesn't support single quoting (which is why went for double quotes eventually).

**Comment by kevinresol** [comment]
ahhh, that's because I didn't update my lix client which writes the hxml
