### ISSUE TITLE
Create possibility for local installations

### ISSUE THREAD

**Issue by grosmar** [lix-pm/lix.client#23]
Like in haxelib or npm you have the possibility to install a dependency locally or globally.
Normally I prefer local installs as it's much cleaner even to reference or browse the sources.

Proposal is to keep the same logic as npm:
everything is local except if you define you want to install it globally.

**Comment by back2dos** [comment]
For browsing source, it works pretty fine these days. For having sources with the repo, it's best to use submodules instead ;)
