### ISSUE TITLE
show dependencies under 'HAXE DEPENDENCIES' in vscode

### ISSUE THREAD

**Issue by sh-dave** [lix-pm/lix.client#27]
I'm not quite sure if this is a lix issue or vshaxe/haxeshim/switchx or where to even start looking at whats going on, but it would be nice if lix managed libraries would show up under the 'HAXE DEPENDENCIES' tab in vscode.

![image](https://user-images.githubusercontent.com/13007175/35432923-f3cef93a-0281-11e8-8081-e70e72ddf239.png)

My setup is on windows 10, vscode 1.19.2, lix 0.14.0, haxeshim 0.12.2, switchx: 0.14.6 and i tried to point the completionserver to the local haxeshim managed one via settings.json:
```json
    "haxe.executable": "node_modules/.bin/haxe.cmd"
```

In the screenshot it shouldn't even point to hxnodejs 4.0.9 but 6.9. I generally use the github versions of the libraries (`lix install gh:...stuff...`) and not haxelib ones in case it matters. I think the 4.0.9 only shows up b/c i also have it installed via haxelib.

**Comment by back2dos** [comment]
Yeah. AFAIK vshaxe is hardwired to use haxelib, so I guess we'd have to fix it there.

**Comment by back2dos** [comment]
AFAIK this now works, because we're hijacking `haxelib path`.
