### ISSUE TITLE
Deploy through travis

### ISSUE THREAD

**Issue by back2dos** [lix-pm/lix.client#32]

**Comment by kevinresol** [comment]
And package it: https://github.com/zeit/pkg

**Comment by kevinresol** [comment]
If we want to have a standalone executable we will need to package each of the commands (lix.js, haxeshim.js, etc) but that would be redundant and wasteful. Another option is to package all of the functionalities into a single monolithic package and install individual commands as aliases (lix, haxe,  etc) on the system. But the best is remove the shims and move them into the compiler. @back2dos do you have any insider news from the HF?

Anyway I will look into using travis to deploy the scripts to npm soonish.

**Comment by back2dos** [comment]
I guess we're done here. If you wanna look into `pkg`, feel free to open a separate ticket. I think depending on node+npm is just fine and we have bigger fish to fry ;)
