### ISSUE TITLE
Installer: check PATH after installation

### ISSUE THREAD

**Issue by gene-pavlovsky** [lix-pm/lix.client#46]
If a user already has `haxe` in his PATH, the lix installer displays an error when it tries to run `haxe --run show-version`.

The last part of `npm install lix -g` looks like this:
```
lix@15.3.0-alpha.1 postinstall C:\Users\username\AppData\Roaming\npm\node_modules\lix
node bin/postinstall.js
Error: Could not process argument show-version
invalid character: -
C:\Users\username\AppData\Roaming\npm
`-- lix@15.3.0-alpha.1
```

In this case the user assumed that the `lix` install had failed.

So it seems that after `lix` is installed, it tries to run `haxe --run show-version` using whatever `haxe` is first in `PATH`, which might not be the command the `lix` one. By the way, does `lix` install some version(s) of `haxe` when it is installed?

I think it would be an improvement if `lix` checks if it's `haxe` is present in PATH as the first match, and if not, tell the user which particular dir must be added to PATH (with a mention of precedence in case there are other `haxe` in PATH already), instead of trying to run `haxe --run show-version`.

Note:
- `lix use haxe 3.4.7` produced an error unknown haxe version or smth like that
- `lix haxe-versions` printed an empty list
- `lix install haxe 3.4.7` downloaded 3.4.7 and set is as default
Does it sound correct?

**Comment by back2dos** [comment]
Should work now.
