### ISSUE TITLE
Forbidden on Travis macOS while lix install

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#49]
I have no idea why it [fails on mac](https://travis-ci.org/kevinresol/tink_core/jobs/418557950#L119) but [ok on linux](https://travis-ci.org/kevinresol/tink_core/jobs/418557949#L480)

**Comment by kevinresol** [comment]
I suspect the request is blocked by the GitHub's rate limiter. I think many people are bombarding the GitHub server from that same VM / IP address.

**Comment by kevinresol** [comment]
I am pretty sure it is caused by the rate limiter. But I think we still need a solution.

**Comment by back2dos** [comment]
Hmm. Technically, you shouldn't be calling `lix install` in the CI. But yeah, we should still fix this somehow ^^

**Comment by kevinresol** [comment]
how about introducing a credential file? e.g. `~/.lix/credentials` containing Gitlab and Github credentials. And we can get rid of the command line flag, which is insecure.

We can also support environment vars e.g. `LIX_GITHUB_TOKEN`

But the current command line parser looks like a mess and I don't really want to touch it...

**Comment by back2dos** [comment]
Should be handled via #109
