### ISSUE TITLE
Module undefined requires node.js version 4.0.0 or higher

### ISSUE THREAD

**Issue by darmie** [lix-pm/lix.client#55]
I use nodejs `v8.11.3` and `v10.8.0`

Is this a compatibility problem. How do I resolve. Also it doesn't co-operate with visual studio Haxe extension.

**Comment by kevinresol** [comment]
Looks like I compiled with some old hxnodejs or sth. Can you try `lix@15.3.2` again?

**Comment by kevinresol** [comment]
Please reopen if problem persists.
