### ISSUE TITLE
Feature request: private GitHub dependencies without adding a token to the hxml

### ISSUE THREAD

**Issue by tbrosman** [lix-pm/lix.client#56]
Currently to add private dependencies you have to add a token to the hxml. Looking at the code, it looks like this is because the GitHub source in lix uses the GitHub API rather than automating Git. There are pluses and minuses to this approach: it's much simpler than automating Git, but at the same time you can't use the effective environment (e.g. whatever keys ssh-agent is set up with) to access repositories. One additional advantage of using Git automation over API calls: it would work for both GitLab and GitHub without needing separate sources for each.

My current workaround is to use Git submodules for private repo dependencies and simply add them to my classpath. It's sub-optimal (I would much rather use lix for everything 😄) but works.

**Comment by kevinresol** [comment]
I think you can already do this:

```
lix install git:git@github.com:lix-pm/lix.client.git
```

**Comment by kevinresol** [comment]
Not that if you use the https url then you are not using ssh, which is mentioned in your OP.

**Comment by tbrosman** [comment]
Ah, fair point. In my case either is sufficient :) I'm just more used to the ssl-style auth setup.
