### ISSUE TITLE
Git libraries in lix library cache are named "0.0.0"

### ISSUE THREAD

**Issue by tbrosman** [lix-pm/lix.client#57]
Under my roaming folder:

`C:\Users\Me\AppData\Roaming\haxe\haxe_libraries\`

I have a file named "0.0.0" which corresponds to a library I checked out via git (see #56):

`lix install git:https://www.github.com/username/my_lib.git`

I have a haxelib.json in the root of the repo with the version and name specified. lix picks up on this when I add the library to my scope:

`mounting as my_lib#0.0.1`

Why does the folder in the library cache not reflect this?

**Comment by kevinresol** [comment]
Looking at the code I think it is an implementation detail that you shouldn't worry about: the reason is that lix uses the same local git repo for all "versions" of the library.

**Comment by kevinresol** [comment]
Can't reproduce.

```
lix install git:https://www.github.com/haxetink/tink_core.git
```

generates this:

```
-cp ${HAXE_LIBCACHE}/tink_core/1.18.0/git/98f25aa1691d343f8459b4fbcb47b5eef815f898/src
```

**Comment by tbrosman** [comment]
Thanks for taking a look! I'll try to get a more specific repro. I think the name isn't coming back properly in my case. Looking at Git.hx:82, the destination path is computed based on name and version:

```
dest: Computed(function (l) return [l.name, l.version, 'git', sha]),
```

So I'm guessing l.name is null.

**Comment by tbrosman** [comment]
@kevinresol I confirmed this is gone in 15.3.2 (my client was at 15.1.0-rc.2).
