### ISSUE TITLE
git:https://github.com should not fallback to the github (http zip) route

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/lix.client#58]
I think people have good reasons to use `git:` (see #56)

**Comment by back2dos** [comment]
This is mostly because if you have a haxelib compatible `haxelib.json` that should point to github dependencies, you need to use `git:` urls, Although this could be handled a bit more intelligently (i.e. only translate to `github:` if the URL is from a `haxelib.json`).

**Comment by kevinresol** [comment]
Current workaround is to add a `www`
e.g. `git:https://www.gitlab.com...`

https://github.com/lix-pm/lix.client/blob/2b4cc45d921c538a0205e00ba0959ccb0915e55b/src/lix/client/sources/Git.hx#L50
