### ISSUE TITLE
downloading dependencies from haxelib fails for multiple tink libraries on linux

### ISSUE THREAD

**Issue by sh-dave** [lix-pm/lix.client#6]
I'm not sure if this is the right place for the issue (or even somehow useful info), but anyways:

I just tried to build a project on a new install of ubuntu 16 and running ```lix download``` fails for multiple tink libraries (getting the zips from https://lib.haxe.org/p/.../download)

- tink_json 0.4.0
- tink_streams 0.2.0
- tink_stringly 0.1.0
- tink_typecrawler 0.4.0
- tink_url 0.2.0

it works for
- tink_core 1.9.1
- tink_io 0.5.0
- tink_macro 0.13.3

The error i get is
```
events.js: 163
    throw er;

Error: incorrect header check
    at Zlib._handle.onerror(zlib.js:355:17)
```

I then installed every failed library again with f.ex ```lix install gh:haxetink/tink_json#0.4.0``` (this time getting the zips from https://github.com/haxetink/tink_LIB/archive/COMMIT.tar.gz), and everything downloads and unzips ok.

**Comment by back2dos** [comment]
Yeah, I noticed this myself. The thing is the haxelib server is very liberal with it's `Content-Type` headers, which is why `lix download` doesn't get that it's a `.zip` and then treats it as `.tar.gz` (open formats FTW \o/). I did make the client [check the url](https://github.com/lix-pm/switchx/blob/master/src/switchx/Download.hx#L38) though. If you update the client it should work (and complain that the download directive is in a deprecated format, because I needed to change a few things).

**Comment by sh-dave** [comment]
Ah yes, updating lix and switch shows a (somewhat obscure :thinking: ) warning now.

**Comment by back2dos** [comment]
Yeah, sorry about the obscurity. For all haxelib devs you should just rerun `lix install haxelib:theLib` and the warning goes away ;)

**Comment by sh-dave** [comment]
On my part, i didn't intend to use the haxelib versions at all, but dependencies are pulled by default from it, it seems. Just tried with adding tink_json from github and this is what i get in the corresponding hxml files:
```
# @install: lix --silent download https://github.com/haxetink/tink_json/archive/5c9bffe51457d4258c263042160e2ae5cca7eff0.tar.gz into tink_json/0.5.0/github/5c9bffe51457d4258c263042160e2ae5cca7eff0

# @install: lix --silent download haxelib:tink_core#1.9.1 into tink_core/1.9.1/haxelib 
# @install: lix --silent download haxelib:tink_macro#0.13.3 into tink_macro/0.13.3/haxelib
# @install: lix --silent download haxelib:tink_typecrawler#0.5.0 into tink_typecrawler/0.5.0/haxelib 
```

**Comment by back2dos** [comment]
Yep, that looks about right - crazy as that may sound ^^
