### ISSUE TITLE
Dependencies should resolve from .haxerc if present instead of haxelib.json

### ISSUE THREAD

**Issue by starburst997** [lix-pm/lix.client#64]
Maybe that's already the case and didn't notice, but let's say I have dependencies that do use "lix", instead of reading the additional dependencies from the haxelib.json, I think it should try to resolve them from their haxe_libraries directory, as far as I know there is no way to specify a git repo in haxelib.json right?

**Comment by back2dos** [comment]
Both haxelib and lix support git urls in haxelib.json, e.g. https://github.com/DoclerLabs/hexMachina/blob/master/haxelib.json#L12 (I think you can add the hash/tag/branch as fragment identifier). 
Beyond that, lix will allow any URI processable by `lix download` in haxelib.json, e.g. https://github.com/MVCoconut/coconut.react/blob/master/haxelib.json#L15

That said, the information in haxe_libraries should probably be used too, at least if haxelib.json doesn't specify a version.

**Comment by starburst997** [comment]
Thanks you!!
