### ISSUE TITLE
vshaxe's eval-debugger doesn't work with Lix/Haxeshim (Haxe 4RC2, scoped or global Lix-installed Haxe)

### ISSUE THREAD

**Issue by fullofcaffeine** [lix-pm/lix.client#72]
I don't know whether this is a `lix` or `haxeshim` issue (or, less-likely a vshaxe `eval-debugger` issue).

* vshaxe v2.8.0
* vscode v1.32.3 (linux)
* Linux Mint 18.3
* Lix 15.3.6
* Haxe 4RC2

I have a local lix scope in my project set to Haxe 4RC2. In vshaxe, there's no custom config for the haxe executable (default is just `haxe`). After `lix download`ing everything, completion works as expected in `vshaxe`.

Here's a dump of my vshaxe settings.json:

`global settings`:
```
{
 "haxe.enableCompilationServer": false
}
```

`workspace settings`:
```
{
  "haxe.displayConfigurations": [["build-frontend.hxml"],["build-backend.hxml"]],
}
```

Then, I have the following launch.json for the workspace, to configure the eval-debugger debugging launch target:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Haxe Interpreter",
			"type": "haxe-eval",
			"request": "launch",
		}
	]
}
```

When I go the `Debug` section of vscode and launch the debug build: 

![vshaxe1](https://user-images.githubusercontent.com/81248/55270571-eba2cb80-5265-11e9-91f5-013da2d2371e.png)

It ends up failing with the following message:

`classpath src is not a directory or cannot be read from`

![vshaxe2](https://user-images.githubusercontent.com/81248/55270575-f5c4ca00-5265-11e9-85dc-f1e3fee8d96a.png)

The `src` directory *is* present in the workspace, it's part of my project's directory's tree:

```
├── app.js
├── build-backend.hxml
├── build-frontend.hxml
├── haxelib.json
├── haxe_libraries
├── makefile
├── node_modules
├── package.json
├── README.md
├── release_haxelib.sh
├── src //<--- here
├── webpack.config.js
└── yarn.lock
```

Also, as you may see, I have two hxmls, as this projects includes code for the frontend and the backend of the app. Right now, `build-backend.hxml` is only a placeholder as I haven't got to implementing it yet, so both files have the following contents:

```
-lib haxe-loader
-lib react

-cp src
-js app.js
-main App

-D react_hot
```

Perhaps this a Haxeshim bug? Any insights and or workarounds would be greatly appreciated.

There's some additional information in the discussion [here](https://pastebin.com/Rc1ivEmG) and [here](https://pastebin.com/1Wv9DPrt).

Thanks!

**Comment by kevinresol** [comment]
Would be nice if you can reduce this to minimum and put it on a separate repo.

**Comment by fullofcaffeine** [comment]
Here's a minimalist project to reproduce the problem: https://github.com/fullofcaffeine/haxe-vscode-lix-macro-debugger. `Main.hx` has the `Main` class and a simple expression macro.

Haxe 4RC2 is installed globally (It seems the eval-debugger extension can't find a scoped Lix-installed Haxe, and tells me I have an old version of Haxe and that the eval-debugger requires at Haxe 4RC2, so I had to install Haxe 4 RC2 globally, see: https://www.collabshot.com/show/c7ddfe) and @ a local scope using Lix.

* Scenario 1 - without Lix:

If I force-set Haxe to the unwrapped/native binary @ `/usr/bin/haxe`, the eval debugger works fine:
![issue1](https://user-images.githubusercontent.com/81248/55536562-4f1e6600-5677-11e9-9a94-b4cc78b16af4.png)

__I left this as a default setting in https://github.com/fullofcaffeine/haxe-vscode-lix-macro-debugger/blob/master/.vscode/settings.json__.

* Scenario 2 - Using Lix.

I assume that to use Lix, it's just a matter of leaving the default `haxe.executable` setting in vshaxe so that the wrapped/shim version of Haxe is called instead. So, to test this scenario, remove the `haxe.executable` setting in: https://github.com/fullofcaffeine/haxe-vscode-lix-macro-debugger/blob/master/.vscode/settings.json or change it to `'haxe'`.

When using Lix, after clicking the Launch button :play_or_pause_button: in the debug section, it fails and the following message is shown in the debug output pane:

`classpath src is not a directory or cannot be read from`.
![issue2](https://user-images.githubusercontent.com/81248/55536875-221e8300-5678-11e9-9329-f9f61713d011.png)

It seems this could be a problem both with the eval-debugger and Lix. With eval-debugger for not using/finding the scoped Lix-installed Haxe and falling back to the global version, instead. With Lix because once eva-debugger finds it (the globally Lix-installed Haxe), it fails with the message above. It only works when vshaxe is setup to a global raw/un`Lix`ed installation of Haxe 4RC2.

**Comment by kevinresol** [comment]
I cloned the repo and pressed the play button in the debug panel. It tells me:

`eval-debugger requires Haxe 4.0.0-rc.2 or newer, found 4.0.0-rc.1+1fdd3d5`

Obviously the project is using rc2 which is specified in `.haxerc` and that `4.0.0-rc.1+1fdd3d5` is specified my global lix scope.

@Gama11 how is haxe invoked by the debugger?

**Comment by kevinresol** [comment]
With the linked PR I am able to run the debugger 😄 

<img width="1552" alt="Screen Shot 2019-04-24 at 1 29 18 PM" src="https://user-images.githubusercontent.com/1103788/56634554-fdc12f80-6694-11e9-9f17-b1f8e8b7bb31.png">
