### ISSUE TITLE
Lix defaults to outdated stable version

### ISSUE THREAD

**Issue by Gama11** [lix-pm/lix.client#78]
Lix version `15.4.0`.

After installing Lix, `node_modules/.bin/haxe -version` prints 3.4.2. I get why it doesn't use a preview build, but why would it default to a build that old? Is there any good reason not to use the latest stable version 3.4.7 instead?

**Comment by back2dos** [comment]
It should. Unless you've ever had lix installed before?

**Comment by Gama11** [comment]
Hm, yes I did quite a while ago.. probably around the time when 3.4.2 was the latest stable. :) I guess I didn't quite get rid of all traces as I thought I had...

I guess this can be closed then? Or is that something that can be improved so that Lix cleans up after itself when it's uninstalled?

**Comment by Gama11** [comment]
Perhaps the cleanup would be covered by https://github.com/lix-pm/haxeshim/issues/23?

**Comment by back2dos** [comment]
Yeah, uninstalling should clean up properly.
