### ISSUE TITLE
Unable to resolve nightly version nightly build 

### ISSUE THREAD

**Issue by markknol** [lix-pm/lix.client#82]
I did `yarn lix download` (on the _mvcoconut.github.io_  repo)
Then I got
```
Looking up Haxe version "f60693d" online
Unable to resolve nightly version nightly build f60693d locally, install it first with `lix install haxe nightly build f60693d`
```
So I did `yarn lix install haxe nightly build f60693d`
```
$ lix install haxe nightly build f60693d
too many arguments

error Command failed with exit code 500.
``` 
I also tried `yarn lix install haxe f60693d`, but then got
```
Looking up Haxe version "f60693d" online
Unable to resolve nightly version nightly build f60693d locally, install it first with `lix install haxe nightly build f60693d`

error Command failed with exit code 404.
```
I don't know if the nightly version doesn't exist or I use the wrong parameters. Either way, I think the command-suggestion that lix gives, is not correct.

**Comment by kevinresol** [comment]
apparently f60693d is not listed in build.haxe.org?

**Comment by back2dos** [comment]
Well, apparently nightlies get deleted after 1 year. Probably should do something about that. Still, the error message is definitely off ^^

**Comment by nadako** [comment]
Can't install latest nightly (`73a85bf`) too. It is on build.haxe.org (https://build.haxe.org/builds/haxe/windows64/), but still can't be resolved, probably because of some changes @andyli recently done on the build server?

**Comment by nadako** [comment]
Hm, the code points to http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe (https://github.com/lix-pm/lix.client/blob/e32d580819d7ad337e2aa945c68ee5e374c8d854/src/lix/client/haxe/Switcher.hx#L29), which indeed only has older versions. Maybe just using https://build.haxe.org/builds/haxe/ will fix the issue?

**Comment by andyli** [comment]
Yeah, previously the index file is generated during CI and uploaded to the S3 bucket. It's now a lambda function and we no longer generate/upload the index file, so the index in the S3 web url (amazonaws.com) is outdated. Please use build.haxe.org instead.

**Comment by back2dos** [comment]
Fixed in https://github.com/lix-pm/lix.client/pull/86
