### ISSUE TITLE
"Not found" when trying to download a Haxe nightly

### ISSUE THREAD

**Issue by Gama11** [lix-pm/lix.client#89]
Not sure what changed, but all of the sudden, downloading nightlies doesn't work anymore again:

```
>npx lix download haxe nightly
Looking up Haxe version "nightly" online
  Resolved to nightly build 24b8830. Downloading ...
Not Found
```

https://build.haxe.org/builds/haxe/windows/ looks normal to me.

**Comment by Gama11** [comment]
It's happening again.. :/

```
Looking up Haxe version "nightly" online
  Resolved to nightly build 97d365b. Downloading ...
Not Found
```

**Comment by AlexHaxe** [comment]
Apparently it happens, when current/file date and date encoded in filename don't match up.
Version 0d88c58 is another example of it.

**Comment by AlexHaxe** [comment]
still broken for current nightly (d8c9cd0)

**Comment by back2dos** [comment]
@andyli I very vaguely remember that in one of your twitch videos you queried some amazon API for a JSON file of the different versions. Is that URL publicly available?

**Comment by andyli** [comment]
That json only has released version, it's here https://haxe.org/website-content/downloads/versions.json

**Comment by JordanPlayz158** [comment]
This issue appears back "Unable to resolve nightly version 5fdb166 locally, install it first with `lix install haxe 5fdb166`" I even tried to follow the readme and tried to use stable haxe branch but "No stable build found"

**Comment by AlexHaxe** [comment]
I don't think you can still download nightlies from 2020. oldest I see is from march 2021.

**Comment by kevinresol** [comment]
the official host for nightly only keep them for a year

**Comment by JordanPlayz158** [comment]
Oh, does lix get the haxe version of a project and try to retrieve it as I was just trying to install latest

**Comment by kevinresol** [comment]
if you want to revive an old project that relied on nightly you might have luck trying the closest stable release of that nightly

**Comment by back2dos** [comment]
Also IIRC the URLs for builds changed at some point and older lix versions are still pointed to the old URLs.

**Comment by JordanPlayz158** [comment]
Oh, my lix version was latest
