### ISSUE TITLE
Some js exception before haxe compiles (though compilation works)

### ISSUE THREAD

**Issue by emugel** [lix-pm/lix.client#93]
Upon running `haxe myproject.hxml` there is some sort of js exception shown it seems:

```
events.js:187
throw er; // Unhandled 'error' event
^
Error: write EPIPE
at afterWriteDispatched (internal/stream_base_commons.js:150:25)
at writeGeneric (internal/stream_base_commons.js:141:3)
at Socket._writeGeneric (net.js:768:11)
at Socket._write (net.js:780:8)
at doWrite (_stream_writable.js:431:12)
at writeOrBuffer (_stream_writable.js:415:5)
at Socket.Writable.write (_stream_writable.js:305:11)
at H.path (/usr/lib/node_modules/lix/bin/haxelibshim.js:2:86322)
at H.dispatch (/usr/lib/node_modules/lix/bin/haxelibshim.js:2:87495)
at H.main (/usr/lib/node_modules/lix/bin/haxelibshim.js:2:85725)
Emitted 'error' event on Socket instance at:
at errorOrDestroy (internal/streams/destroy.js:107:12)
at onwriteError (_stream_writable.js:446:5)
at onwrite (_stream_writable.js:473:5)
at internal/streams/destroy.js:49:7
at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:7:3)
at Socket.destroy (internal/streams/destroy.js:37:8)
at afterWriteDispatched (internal/stream_base_commons.js:150:17)
at writeGeneric (internal/stream_base_commons.js:141:3)
at Socket._writeGeneric (net.js:768:11)
at Socket._write (net.js:780:8) {
errno: 'EPIPE',
code: 'EPIPE',
syscall: 'write'
}
haxelib run hxcpp Build.xml haxe -Ddebug .... <etc, then it compiles fine>
```

So seems some pipe error `{errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }`. 
After that, the project is compiled fine.

As to a *possible* cause of the error:
* had a particular lib that I at one point wanted to publish, but its haxelib.json had a problem (`"dependencies": { "tink_concurrent", "haxe-strings" }`  instead of `"dependencies": { "haxe-strings": "", "tink_concurrent": "" }`).
* when `lix install` that lib, it produced a similar kind of mess-up (js exception it seemed with different message though, something like `wrong output "tink_concurrent", ). 
* fixed the erroneous haxelib.json, removed the file from `haxe_libraries/`, did a `lix install git:myserver:/path/to/repo` again.

If it's because of that or another reason I don't know, but I prefer to ask for advice. 
Again, the project compiles, it's an unpleasant exception though...

**Comment by emugel** [comment]
Update:
Have just installed haxe4 rc5 with lix and made a git branch for it. No such message with haxe4.
 
Changing branch back to haxe3 and switching version brings back the previous message before compilation.

**Comment by back2dos** [comment]
Phew. Sounds like haxe3 is closing some stdio pipe prematurely or something ...

Could you please try to reduce it to a minimal example?

**Comment by emugel** [comment]
Oh right yes I should try on some fresh new project, or same scope but different hxml. Will do tomorrow :)

**Comment by emugel** [comment]
* Taking back previous comment, it's not because of loopback (when loopback works there is still the same message as in original post).
* Taking back what I wrote yesterday on gitter (`undefined` I got was because I debugged too hurriedly, tracing a var before it was initialized...)

So here are the facts:

* when my pretty big project has errors, it fails quickly and no symptoms of this issue appear (both Haxe 3 and 4).
* when no errors, it takes longer and the symptoms appear.

The latest development is adding one single `console.error("")` in js in function haxeshim_Resolver **also removes** the symptoms:
```
var haxeshim_Resolver = function(cwd,libDir,mode,defaults) {
	console.error("_Resolver new  cwd="+ cwd + " libDir=" + libDir + " mode="+mode + " defaults="+defaults); // <- this makes the symptom dissapear

	this.cwd = haxe_io_Path.addTrailingSlash(haxe_io_Path.normalize(cwd));
	this.libDir = libDir;
	this.mode = mode;
	this.defaults = defaults;
};
```
Is it my shitty computer that compiles hxcpp too slowly for the pipes used by lix? Maybe some timeout somewhere? Or something else. 
I have no idea....

Interestingly changing that `console.error` to a `console.log` reproduces the symptoms. I think because according to the docs `console.error` is unbufferized while the other is not.

Any suggestion or idea? ^^

**Comment by emugel** [comment]
*A few days later...*

Ok my loopback problems are definitely fixed (something in my distro). But the bug remains. Even with the `console.err("xxx")` above I still get occasional exceptions, they never prevent compilation nor seem to have any other impact than visual. The exceptions also sometimes are different...

I won't bother for now. Will keep this bug open until someday I find a fix; maybe some other people will get it eventually (I wish, haha).

**Comment by emugel** [comment]
Update: when build.hxml is configured withe.g. `--connect 6878` there are no such warnings

**Comment by back2dos** [comment]
Reproduced here: https://github.com/lix-pm/haxeshim/issues/56
